#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake $targetType usertwoPhaseMixture
wmake $targetType userinterfaceProperties
wmake $targetType usertwoPhaseProperties
wmake $targetType userincompressibleTwoPhaseMixture
wmake $targetType userimmiscibleIncompressibleTwoPhaseMixture
wmake $targetType usertwoPhaseChange

#------------------------------------------------------------------------------
